#!/bin/sh
# This script creates a Uc pairs file that contains all the mapped reads in the input bam file.
# output is bgzipped and pairix-indexed.
 
input_bam=$1
prefix=$2
echo "## pairs format v1.0" > $prefix.bsorted.pairs
echo "#sorted: chr1-chr2-pos1-pos2" >> $prefix.bsorted.pairs
echo "#shape: upper triangle" >> $prefix.bsorted.pairs
echo "#columns: readID chr1 pos1 chr2 pos2 strand1 strand2" >> $prefix.bsorted.pairs
echo "#command: bam2pairs $input_bam $prefix" >> $prefix.bsorted.pairs
samtools view -F12 $input_bam | parse_line.pl -5 - |sort -k2,2 -k4,4 -k3,3n -k5,5n >> $prefix.bsorted.pairs
bgzip -f $prefix.bsorted.pairs
pairix -f $prefix.bsorted.pairs.gz

